### ISSUE TITLE
手动安装补充

### ISSUE THREAD

**Issue by chengked** [HamCQ/flarum-ext-card-show-community#1]
感谢大佬对flarum社区的支持，由于当前未发布版本，只能通过手动的方式安装
1、composer.json中添加如下
```js
"repositories":[
           {
                    "type":"path",
                    "url":"/flarum安装目录/vendor/hamcq/flarum-ext-card-show-community"
            }
    ],
```
2、`composer require hamcq/picture-show-community:@dev`
3、由于需要阿里云短信支持，故使用注释掉这块
![image](https://github.com/HamCQ/flarum-ext-card-show-community/assets/82382272/86263694-d683-4bf2-9d15-02f322e27186)

**Comment by Eminlin** [comment]
感谢提醒。已发布版本

https://packagist.org/packages/hamcq/picture-show-community
